name: "Flake8GithubWikiAction"
description: "Generate current Flake8 stats to a Github Wiki Page"
inputs:
  check-destination:
    description: "Path to code to check"
    required: true
  wiki-repo:
    description: "Wiki repo"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    check_destination: ${{ inputs.check-destination }}
    wiki_repo: ${{ inputs.wiki-repo }}
