name: "Flake8GithubWikiAction"
description: "Generate current Flake8 stats to a Github Wiki Page"
inputs:
  check_destination:
    description: "Path to code to check"
    required: true
  wiki_repo:
    description: "Wiki repo"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.check_destination }}
    - ${{ inputs.wiki_repo }}
