name: "Flake8 Results to Github Wiki"
author: "Paul Davidson"
description: "Generate current Flake8 stats to a Github Wiki Page"
inputs:
  check-destination:
    description: "Path to code to check"
    required: true
  path-to-wiki-repo:
    description: "Path to Wiki repo"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.check-destination }}
    - ${{ inputs.path-to-wiki-repo }}
branding:
  icon: 'pie-chart'
  color: 'orange'